
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-09
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-09
pull_requests: [{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-add-post-put","number":41,"title":"lc - Add update of \"section\" to POST and PUT for roster student","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/41"},{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-dev10","number":39,"title":"Add an optional remove from organization to course staff delete + tests ","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/39"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-assignment-repository","number":37,"title":"sc assignment repository","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/37"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-assignment-entity","number":36,"title":"sc assignment entity","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/36"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-assignment-db","number":31,"title":"sc assignment db","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/31"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-create-title","number":30,"title":"lc - Change title of site from \"Vite + React\" to \"Frontiers\"","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/30"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-Update-help-page-with-ignored-fields","number":29,"title":"Db update help page with ignored fields","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/29"},{"author":{"id":"U_kgDOCNoTQw","is_bot":false,"login":"dkim876","name":""},"headRefName":"dk-csv-formats-help-icon","number":22,"title":"dk - add csv upload format help icon and test","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/22"},{"author":{"id":"U_kgDOCM7ecQ","is_bot":false,"login":"davidbazan383","name":""},"headRefName":"DB-Update-help-page-with-team-column","number":21,"title":"DB-Updated the Help Page (CSV Download Section) to include the teams â€¦","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/21"}]
