
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-09
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-09
pull_requests: [{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-dev10-backend","number":50,"title":"oty - Add optional BACKEND deleteFromOrg selection on for coursestaff (+tests)","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/50"},{"author":{"id":"U_kgDOCFV2Vw","is_bot":false,"login":"laurenc06","name":"Lauren Cho"},"headRefName":"lc-dry-signin","number":49,"title":"lc -  REFACTOR: Dry up the SigninPage and PromptSigninPage","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/49"},{"author":{"id":"U_kgDOBsZdzQ","is_bot":false,"login":"samc005","name":""},"headRefName":"sc-assignment-post","number":48,"title":"sc assignment post","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/48"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-ux-improvement-student-search","number":45,"title":"Used react-bootstrap-typeahead to improve dropdown UI","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/45"}]
