
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-09
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-09
pull_requests: [{"author":{"id":"U_kgDOCvDUhw","is_bot":false,"login":"oyararbas","name":""},"headRefName":"oy-dev10-frontend","number":56,"title":"Added frontend checkbox to send removeFromOrg to backend","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/56"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-api-delete-assignments","number":55,"title":"Vik api delete assignments","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/55"},{"author":{"id":"MDQ6VXNlcjYxMzI4MDc4","is_bot":false,"login":"viktorinkov","name":"Viktor Stanislavov Minchev"},"headRefName":"vik-reintroduce-eslint-rules","number":51,"title":"fixed es linting","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-09/pull/51"}]
